<?php
defined('BASEPATH') OR exit('No direct script access allowed'); 

$config['rolet_type']   = ["Super Admin", "Admin", "User", "Member"];
$config['civil_status'] = ["Single", "Engaged", "Married", "Divorced", "Widowed"];
$config['citizenship']  = [
	"Afghans",
	"Albanians",
	"Algerians",
	"Americans",
	"Andorrans",
	"Angolans",
	"Antiguans and Barbudans",
	"Argentines",
	"Armenians",
	"Arubans",
	"Australians",
	"Austrians",
	"Azerbaijanis",
	"Bahamians",
	"Bahrainis",
	"Bangladeshis",
	"Barbadians",
	"Basques",
	"Belarusians",
	"Belgians",
	"Belizeans",
	"Beninese",
	"Bermudians",
	"Bhutanese",
	"Bolivians",
	"Bosniaks",
	"Bosnians and Herzegovinians",
	"Botswana",
	"Brazilians",
	"Bretons",
	"British",
	"British Virgin Islanders",
	"Bruneians",
	"Bulgarians",
	"Burkinabés",
	"Burmese",
	"Burundians",
	"Cambodians",
	"Cameroonians",
	"Canadians",
	"Catalans",
	"Cape Verdeans",
	"Chadians",
	"Chileans",
	"Chinese",
	"Colombians",
	"Comorians",
	"Congolese",
	"Costa Ricans",
	"Croats",
	"Cubans",
	"Cypriots",
	"Czechs",
	"Danes",
	"Djiboutians",
	"Dominicans (Commonwealth)",
	"Dominicans (Republic)",
	"Dutch",
	"East Timorese",
	"Ecuadorians",
	"Egyptians",
	"Emiratis",
	"English",
	"Equatoguineans",
	"Eritreans",
	"Estonians",
	"Ethiopians",
	"Falkland Islanders",
	"Faroese",
	"Fijians",
	"Finns",
	"Finnish Swedish",
	"Filipinos",
	"French citizens",
	"Gabonese",
	"Gambians",
	"Georgians",
	"Germans", 
	"Ghanaians",
	"Gibraltarians",
	"Greeks", 
	"Grenadians",
	"Guatemalans",
	"Guianese (French)",
	"Guineans",
	"Guinea-Bissau nationals",
	"Guyanese",
	"Haitians",
	"Hondurans",
	"Hong Kongers",
	"Hungarians",
	"Icelanders",
	"I-Kiribati",
	"Indians",
	"Indonesians",
	"Iranians",
	"Iraqis",
	"Irish",
	"Israelis",
	"Italians",
	"Ivoirians",
	"Jamaicans",
	"Japanese",
	"Jordanians",
	"Kazakhs",
	"Kenyans",
	"Koreans",
	"Kosovars",
	"Kuwaitis",
	"Kyrgyzs",
	"Lao",
	"Latvians",
	"Lebanese",
	"Liberians",
	"Libyans",
	"Liechtensteiners",
	"Lithuanians",
	"Luxembourgers",
	"Macao",
	"Macedonians",
	"Malagasy",
	"Malawians",
	"Malaysians",
	"Maldivians",
	"Malians",
	"Maltese",
	"Manx",
	"Marshallese",
	"Mauritanians",
	"Mauritians",
	"Mexicans",
	"Micronesians",
	"Moldovans",
	"Monégasque",
	"Mongolians",
	"Montenegrins",
	"Moroccans",
	"Mozambicans",
	"Namibians",
	"Naurans",
	"Nepalese",
	"New Zealanders",
	"Nicaraguans",
	"Nigeriens",
	"Nigerians",
	"Norwegians",
	"Omani",
	"Pakistanis",
	"Palauans",
	"Palestinians",
	"Panamanians",
	"Papua New Guineans",
	"Paraguayans",
	"Peruvians",
	"Poles",
	"Portuguese",
	"Puerto Ricans",
	"Qatari",
	"Quebecers",
	"Réunionnais",
	"Romanians",
	"Russians", 
	"Rwandans",
	"Saint Kitts and Nevis",
	"Saint Lucians",
	"Salvadorans",
	"Sammarinese",
	"Samoans",
	"São Tomé and Príncipe",
	"Saudis",
	"Scots",
	"Senegalese",
	"Serbs",
	"Seychellois",
	"Sierra Leoneans",
	"Singaporeans",
	"Slovaks",
	"Slovenes",
	"Solomon Islanders",
	"Somalis",
	"Somalilanders",
	"Sotho",
	"South Africans",
	"Spaniards",
	"Sri Lankans",
	"Sudanese",
	"Surinamese",
	"Swazi",
	"Swedes",
	"Swiss",
	"Syriacs",
	"Syrians",
	"Taiwanese",
	"Tamils",
	"Tajik",
	"Tanzanians",
	"Thais",
	"Tibetans",
	"Tobagonians",
	"Togolese",
	"Tongans",
	"Trinidadians",
	"Tunisians",
	"Turks",
	"Tuvaluans",
	"Ugandans",
	"Ukrainians",
	"Uruguayans",
	"Uzbeks",
	"Vanuatuans",
	"Venezuelans",
	"Vietnamese",
	"Vincentians",
	"Welsh",
	"Yemenis",
	"Zambians",
	"Zimbabweans",
];  
$config['occupation']  = ['Teacher', 'Trycicle Driver', 'Farmer', 'Student', 'Other'];
$config['religion']  = [ 
	"Catholic Church",
	"Islam",
	"Evangelicals (PCEC) ",
	"Iglesia Ni Cristo",
	"Other Religious Affiliations",
	"Non-Catholic and Protestant (NCCP)",
	"Aglipayan",
	"Seventh-day Adventist",
	"Bible Baptist Church",
	"United Church of Christ in the Philippines",
	"Jehovah's Witnesses",
	"Other Protestants",
	"Church of Christ",
	"Jesus Is Lord Church Worldwide",
	"Tribal Religions",
	"United Pentecostal Church (Philippines) Inc.",
	"Other Baptists",
	"Philippine Independent Catholic Church",
	"Unión Espiritista Cristiana de Filipinas, Inc.",
	"The Church of Jesus Christ of Latter-day Saints",
	"Association of Fundamental Baptist Churches in the Philippines",
	"Evangelical Christian Outreach Foundation",
	"None",
	"Convention of the Philippine Baptist Church",
	"Crusaders of the Divine Church of Christ Inc.",
	"Buddhist",
	"Lutheran Church in the Philippines",
	"Iglesia sa Dios Espiritu Santo Inc.",
	"Philippine Benevolent Missionaries Association",
	"Faith Tabernacle Church (Living Rock Ministries)",
	"Others",
];
